language: python

python:
  - "2.7.14"

node_js: "node"

cache:
  directories:
    - $HOME/virtualenv/python2.7.14/lib/python2.7/site-packages
    - node_modules

before_install:
  - cp config.travis.js config.js

install:
  - curl http://lilypond.org/download/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh -o lilypond.sh
  - sh lilypond.sh --batch

script:
  - npm run release

branches:
  only:
    - master

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  repo: GuillaumeNury/LilypondScores
  target_branch: gh-pages
