name: Lilypond Score - Build and publish

on:
  push:
     branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.1

      - name: install dependancies
        run: |
          cp config.ci.js config.js
          curl https://lilypond.org/download/binaries/linux-64/lilypond-2.23.5-1.linux-64.sh -o lilypond.sh
          sh lilypond.sh --batch
          npm install

      - name: build
        run: |
          npm run release

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.DEPLOY_TOKEN }}
